### ISSUE TITLE
Assigning Additional Heaters/ Fans

### ISSUE THREAD

**Issue by raykholo** [Duet3D/RepRapFirmware#119]
I've taken a read through the firmware. 

I see that we've got SAM3/ RADDS support for 9 steppers, but I only see 4 heater designations: https://github.com/dc42/RepRapFirmware/blob/dev/src/RADDS/Pins_RADDS.h#L86

Can you advise on how to define the additional heaters:  I originally wondered if there was a gCode to assign them, but then there is the question of the Arduino Pin vs Logical Pin numbers. 

I also saw you replied to someone in the DuetWifi forum that heaters have to be designated at compile.  

So, need to add pins to that file and recompile the firmware? 

Same question for thermistors (line 79) and endstops (line 70).  

Thank you!

**Comment by dc42** [comment]
You'll need to talk to reprap.org forum user prot0typ1cal or someone else who knows the RADDS board better than I do. Posting here http://forums.reprap.org/read.php?13,569468,page=25 may be a good start.
