### ISSUE TITLE
Heaters without Tools

### ISSUE THREAD

**Issue by timmit99** [Duet3D/RepRapFirmware#136]
I am using a Duet Wifi running RepRapFirmware so control a prototype machine that i am developing. The material processing side of the machine requires external heaters and temperature probes. They are JUST a heater and temperature sensor that i want to control. The only way that i can see to do this right now is to assign the heater and probe to a tool and just not define a drive so it acts just a like a standard heater. Is there a way that i am missing to have control over a heater without having to define each as a tool?

**Comment by dc42** [comment]
Please ask support questions on the forum at duet3d.com.
