### ISSUE TITLE
HTTP headers should be case-insensitive

### ISSUE THREAD

**Issue by Kriechi** [Duet3D/RepRapFirmware#139]
While playing around with the HTTP API, I noticed that some headers and values are compared case-sensitive, which [should be case-insensitive](https://stackoverflow.com/a/5259004).

In order to increase compatibility with different HTTP clients switching from `StringEquals` to a case-insensitive variant would be nice.

Here a few place I found that caused me some headache:
https://github.com/dc42/RepRapFirmware/blob/f437e684e7dd4c991b29ffb2b93db7595c5da05e/src/Duet/Webserver.cpp#L868
https://github.com/dc42/RepRapFirmware/blob/f437e684e7dd4c991b29ffb2b93db7595c5da05e/src/Duet/Webserver.cpp#L871
https://github.com/dc42/RepRapFirmware/blob/f437e684e7dd4c991b29ffb2b93db7595c5da05e/src/Duet/Webserver.cpp#L1542

**Comment by T3P3** [comment]
Please discuss on the forum if this is still an issue.
