### ISSUE TITLE
Printing progress info (incorrectly) uses Z baby step value for current layer calculation

### ISSUE THREAD

**Issue by joaobarros** [Duet3D/RepRapFirmware#155]
When starting a print with a Z offset (using baby stepping for example) the Z offset is considered for the layer info calculation.
I attach a screenshot of 1.20RC2 where my 1st layer just started printing (0.2mm 1st layer, 0.1mm normal layers) and it shows it's already on layer 8:
<img width="1221" alt="screen shot 2018-01-17 at 20 13 03" src="https://user-images.githubusercontent.com/172337/35154037-939002f0-fd20-11e7-9f40-7ece66c722c5.png">

**Comment by T3P3** [comment]
Please check if this is still a problem with the latest RRF/DWC and reopen the issue if it is.
