### ISSUE TITLE
Ramps Fd V 1 support

### ISSUE THREAD

**Issue by rockman256** [Duet3D/RepRapFirmware#174]
Hello!
want to use your firmware on my ramps fd v1 + arduino due + esp 8266 (connected to 1 serial port).
Can you do support this board?

**Comment by dc42** [comment]
You would need to build a firmware variant to support that combination. The existing build for RADDS is probably close to what you need, but you would have to modify at least the following files:
- File Pins_RADDS.h to define which pins are used for which purpose
- The 3 functions at the very end of file Platform.h, to define how step pins are assigned to bit positions
