### ISSUE TITLE
Z-probe already triggered; please cancel print

### ISSUE THREAD

**Issue by janegonz** [Duet3D/RepRapFirmware#200]
I have experienced a handful of events where the Z-probe (BLTouch) was already triggered at the start of the move. The current build (2.01) calls for the printer to stop bed compensation and start the print. Luckily, the first layer doesn't typically dig into the print bed. 
However, this finally resulted in a catastrophic failure and I now have a huge, expensive mess on my hands. I'd like to propose that the print get cancelled in the case that the Z-probe is triggered prior to executing bed compensation to avoid this problem. Thanks.

**Comment by T3P3** [comment]
you can include a check for this using conditional gcode:
https://duet3d.dozuki.com/Wiki/GCode_Meta_Commands
