### ISSUE TITLE
Connection Lost Randomly Duet WiFi

### ISSUE THREAD

**Issue by NightlyFidelis** [Duet3D/RepRapFirmware#208]
Hello, 

I've some lost connection this WE on my Duet Wifi. I was on 1.21 Firmware and Running my 3D printer for 6 months without any issue.

I've upgraded to the latest relase 2.01, upgraded the WifiServer and WebControl and I can't connect to the Duet.
![image](https://user-images.githubusercontent.com/40669833/45979670-1eb69900-c050-11e8-9e4e-890e0e20f5e6.png)

Randomly I'm disconnected and reconnected on the Duet.

**Comment by mentaluproar** [comment]
I get that all the time. I'v always had it.  If you have an ASUS router, disable universal beamforming on the 2.4ghz channel.  The other beamforming settings will have no effect on this issue.  While it doesn't solve the problem, it does make it less frequent.
