### ISSUE TITLE
Add custom macro ability to M915

### ISSUE THREAD

**Issue by Patrik-svobodik** [Duet3D/RepRapFirmware#215]
Hi, would it be possible to add something like R4 that would run stall4.g or add a parameter to send a gcode command, essentially doing the same thing? I want to build a MMU2 and add it to my duet with duex5, so when the loading fails it will cut the tip off

**Comment by T3P3** [comment]
Can you try achieving this with conditional gcodes and discuss on the forum if its not possible.
https://duet3d.dozuki.com/Wiki/GCode_Meta_Commands
