### ISSUE TITLE
Add support for M600

### ISSUE THREAD

**Issue by Patrik-svobodik** [Duet3D/RepRapFirmware#216]
Hi, I am making a lot of feature requests, but it would be nice to have the ability to use M600 for filament change, it would run filchange.g in the sys folder, it would be good

**Comment by dc42** [comment]
Will be in next 2.02RC version.

**Comment by Patrik-svobodik** [comment]
Actually it is not working for me, when I run it from dwc, nothing happens

**Comment by dc42** [comment]
There is a bug in the M600 implementation in RC3, fixed in the forthcoming RC4 release.
