### ISSUE TITLE
[FR] Line Breaks and other popup element types for 12864 Display on M291

### ISSUE THREAD

**Issue by slipstreamliner** [Duet3D/RepRapFirmware#264]
When displaying a message via M291 on the Duet Maestro, the message is displayed correctly but if it is too long for the screen it does not automatically line break and carries across the screen to the right until it's no longer readable.

It would be great to have functionality that will provide either automatic line breaking on the 12864, or give us an escape string to use so that we can put line breaks where we wish.

In addition, the ability to popup a bitmap image as part of an M291 would be excellent and could also be utilized to provide splash-screens and other image popups(such as warnings) on the 12864 driven by Duet Maestro.

Thanks,

David
M3D Team

**Comment by T3P3** [comment]
the wrapping request is captured in https://github.com/Duet3D/RepRapFirmware/issues/723
