### ISSUE TITLE
[RRF 2.02 WIFI 1.22] FTP transfer of large files truncated to 2048 bytes on SD card

### ISSUE THREAD

**Issue by frank26080115** [Duet3D/RepRapFirmware#274]
RRF 2.02 WIFI 1.22

uploading large config.g file and other files into 0:/sys via WinSCP (v5.13.8 build 9278)

the resulting file is truncated to 2048 bytes long, I realized this after it appears that settings at the end of the files were not being applied

when uploading extra large files, the file truncation occurs at the previous multiple of 2048, such as 8196

WinSCP logs show transfer successful without error

uploading via DWC and editing via DWC seems to work fine, I will stop using FTP, it's just easier to upload an entire folder with FTP though, now I will probably write a script to zip up my folder and upload it via DWC, until this FTP bug is resolved

**Comment by T3P3** [comment]
Please check that this is still an issue in the latest release, if possible test with at least one other FTP client. if its still a problem please reopen the issue.
