### ISSUE TITLE
2.03RC2 bed level issue!!!

### ISSUE THREAD

**Issue by TheMrCaveman** [Duet3D/RepRapFirmware#285]
With 2.03 bed level is alway different. Everytime i do a bed level it gives me a different height. See pictures. This is 2 times leveling after each other. 

This works flawles in 2.02, so I am wondering what is the cause of this issue.

2.03 is because of this isue a pain to have a good first layer.

![2 03RC3](https://user-images.githubusercontent.com/9423165/57727757-95adaa00-7692-11e9-8b3d-8e2157d86c26.jpg)
![2 03RC2 issue](https://user-images.githubusercontent.com/9423165/57727761-97776d80-7692-11e9-8e94-ca10ab3e74b6.jpg)

**Comment by T3P3** [comment]
It's best to ask for support on forum.duet3d.com

**Comment by SonicDaHouseCat** [comment]
The same problem here with Duet 0.6 where a 9-factor calibration is performed before printing. Tried 2.03RC2 and 2.03RC1+1. Will downgrade and wait for 2.03RC3.

**Comment by dc42** [comment]
Did you use babystepping? I have recently fixed a bug in 2.03RC2 (probably present in some earlier releases too) whereby the current babystepping offset was applied in the wrong direction after certain operations, such as bed probing.

**Comment by SonicDaHouseCat** [comment]
Yeah, I used babystepping. I will test it in the next RC version.
