### ISSUE TITLE
Possible to have more than 441 probe points allowed for bed mesh compensation?

### ISSUE THREAD

**Issue by smp1300** [Duet3D/RepRapFirmware#305]
Hello, I am using the Duet Wifi to control a 3d printer with a very large bed ( ~4x8 ft). I was wondering if it was possible to increase the number of points allowed for bed mesh compensation. Thank you.

**Comment by cdedwards** [comment]
following

**Comment by T3P3** [comment]
Due to memory limitations it is unlikely that the number of mesh bed points will be increased for Duet 2. If the requirement still exists for Duet 3 then please disuses in the forum.

**Comment by T3P3** [comment]
Forum threads:
https://forum.duet3d.com/topic/37112
https://forum.duet3d.com/topic/32739
https://forum.duet3d.com/topic/31368
