### ISSUE TITLE
Can you create H4 parameter for G0/G1 to go and stop if hit endstop but do not modify anything else ?

### ISSUE THREAD

**Issue by psychotik2k3** [Duet3D/RepRapFirmware#311]
i'm using the duet on a CNC
i use a touchplate as probe to ensure taht my tool is always at the height i want from the ground

BUT as these tools are from different sizes i'm not sure about the margin i have from the maximum Z available

so on my gcode when i go up to clearance etc i use 
G0 Z67  H3 
(max height) followed by a 
M208 Z67 
to put back the limit of 67 mm or else i limit my axis possibility for the next tool.

i tried H1 but then it changes my current position and i loose the job made by the probe.

what i just want is a move with stop if you hit an enstop.
also this would be good for relative coordinates mode.

thanks

**Comment by T3P3** [comment]
Can you use G30 S-1, if not please open a forum thread to explain the requirement in more detail
