### ISSUE TITLE
Incorrect extrusion speed after certain commands

### ISSUE THREAD

**Issue by drentsoft** [Duet3D/RepRapFirmware#315]
I have a Duet 0.85 that sets incorrect extrusion speed after certain commands.

I have been informed that this is reproducable on Duet 0.6, wifi, ethernet and Maestro boards and quote below what I was told.
"I’ve just tested what you said below, and this still seems to happen for me, on firmware 2.04RC1, so I imagine it’s a problem across the board. I’ve asked David [DC42] about it."

**Firmware/Web Version**
1.22
1.22.3

**Expected results:**
G1 E10 F300 extrudes at F300 on each call.

**Actual result:**
G1 E10 F300 extrudes at approximately F600 on the first request then at expected speed until certain commands are run.

**Commands that have been observed to cause the issue: **
G32
G29
cancelling a print (M0?)

**Steps to Reproduce:**
Power on > G28 > Raise head temperature to extrusion temp > G32 > G1 E10 F300 | Extrusion occurs at ~F600 > G1 E10 F300 | Extrusion occurs at F300.
Power on > G28 > Raise head temperature to extrusion temp > G29 > G1 E10 F300 | Extrusion occurs at ~F600 > G1 E10 F300 | Extrusion occurs at F300.
Power on > G28 > Raise head temperature to extrusion temp > Run a print > pause > cancel > G1 E10 F300 | Extrusion occurs at ~F600 > G1 E10 F300 | Extrusion occurs at F300.

Additionally I have observed that any Fxxx setting will result in the same incorrect extrusion speed of around F600.

**Work around**
It seems that calling a non-extrusion G1 after any of these commands resets the speed (e.g. G1 Z5).

I can provide config.g and bed.g files if required however I suspect if this still happens on later firmware this may not be needed.

**Comment by T3P3** [comment]
RRF 1.X is not longer supported
