### ISSUE TITLE
RC1 2.04: M665 not working after G32. Changes intended seem to get calibrated away.

### ISSUE THREAD

**Issue by dgrat** [Duet3D/RepRapFirmware#316]
If I use M665 and G32 the printer prints as if I just use one rod length parameter (as before).
Maybe G32 adjusts M666 and thus reverses the effect of the rod length'?

Before: 
M665 L360.000:360.000:360.000 R169.392 H441.644 B155.0 X-0.369 Y-0.580 Z0.000
M666 X-0.267 Y-0.954 Z1.221 A0.00 B0.00

After
M665 L350.000:360.600:359.800 R168.633 H443.264 B155.0 X-1.420 Y-2.581 Z0.000
M666 X1.200 Y-1.748 Z0.549 A0.00 B0.00

**Comment by T3P3** [comment]
Depending on the type of autocalibration you are asking for in G32, it will adjust the rod length:
https://duet3d.dozuki.com/Wiki/Calibrating_a_delta_printer#Section_Auto_calibration
e.g. 7-factor: as 6-factor but also adjusts the diagonal rod length (M665 L parameter).

If you are using 6 or 8 factor (to not adjust the rod length) and you are still seeing this issue then please upgrade to the latest firmware. If you are still seeing the issue please open a forum thread about it.
