### ISSUE TITLE
Low current after LowVoltagePause

### ISSUE THREAD

**Issue by chernogorsky** [Duet3D/RepRapFirmware#338]
Hi,
It looks like after priter had been paused by LowVoltage, it had some currents set to low.
Then I press resume - it start printing, but stack with no-normal-movement very moment or some time later (mostly on high intensive movement)

its reproduced on 2.0.3, 2.0.4 every time I got caught by low voltage. my current workaround - reboot the printer

; Automatic power saving
M911 S22 R23 P"M913 X0 Y0 G91 M83 G1 Z3 E-5 F1000" ; Set voltage thresholds and actions to run on power loss

;resurrect-prologue.g
M116 ; wait for temperatures
G28 X Y ; home X and Y, hope that Z hasn't moved
M83 ; relative extrusion
G1 E4 F3600 ;

; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v2 on Fri May 24 2019 16:24:21 GMT+0300 (Israel Daylight Time)
M83            ; relative extruder moves
G1 E-10 F3600  ; retract 10mm of filament
G91            ; relative positioning
G1 Z5 F360     ; lift Z by 5mm
G90            ; absolute positioning
G1 X0 Y0 F6000 ; go to X=0 Y=0

; resume.g
; called before a print from SD card is resumed
;
; generated by RepRapFirmware Configuration Tool v2 on Fri May 24 2019 16:24:21 GMT+0300 (Israel Daylight Time)
G1 R1 X0 Y0 Z5 F6000 ; go to 5mm above position of the last print move
G1 R1 X0 Y0          ; go back to the last print move
M83                  ; relative extruder moves
G1 E10 F3600         ; extrude 10mm of filament

**Comment by T3P3** [comment]
You are setting the X any Y motors to 0 current in the M911 command but I don't see anywhere you setting it back to the normal current. try adding M913 X100 Y100 to the resurrect prolog file. If that does not solve the issue please try with the latest release, if still no luck please open a forum thread about this.
