### ISSUE TITLE
Z axis Configuration bug when using the RRF Config tool

### ISSUE THREAD

**Issue by JoshWobbles** [Duet3D/RepRapFirmware#347]
I just updated to RRF 3, and created a new config for my Ender 3 Pro, but I get "Failed to Enable Endstops" for my Z axis.

I use the original endstop switch and have no z probe installed or configured.

**Comment by JoshWobbles** [comment]
I believe the issue lies in the RRF config builder, the default settings do not have a endstop pin assigned for Z 
![2020-01-05_10-15-15](https://user-images.githubusercontent.com/18446288/71782104-642c7a80-2fa4-11ea-8fd8-3581d5072361.jpg)

**Comment by JoshWobbles** [comment]
Now I'm getting heater faults for the bed.

Somebody needs to take a look at the default Ender 3 / RRF 3 settings because there seem to be some issues.

**Comment by Billtopia** [comment]
On the CR-10s I had heat bed issues and ran the PID tuning on it and it solved the error... did you try that?

**Comment by x0rtrunks** [comment]
Z endstop is properly selected now.
