### ISSUE TITLE
Question on "Stepper brake configure: M594 #275"

### ISSUE THREAD

**Issue by shadrincev** [Duet3D/RepRapFirmware#351]
Good afternoon, how are things with [Stepper brake configure: M594](https://github.com/dc42/RepRapFirmware/pull/275). Will it be added to the firmware? Or if added, how it is configured. Thanks.

**Comment by dc42** [comment]
Stepper brake configuration was added in RRF 3.4. See https://docs.duet3d.com/en/User_manual/Reference/Gcodes#m5697-configure-motor-brake-port.
