### ISSUE TITLE
gcode files left open upon error

### ISSUE THREAD

**Issue by cdedwards** [Duet3D/RepRapFirmware#354]
Just upgraded to v3.01rc1 this morning. Changed config.g and attempted to home the printer. Needed to edit the homey.g and homex.g to change the S parameter of G1 to an H, but when I attempted to save the file after running the broken .g files, I recieved the error that duet was unable to delete the file and I'm left with a homey.g.part in the directory and a homey.g file which is just the old file. Expected behaviour would be that upon error, the file would be closed and changes could be made without resorting to a M999

**Comment by T3P3** [comment]
A file that is being executed cannot be edited. wait for the macro to finish before attempting to edit the file.
