### ISSUE TITLE
M574 'S4' option error

### ISSUE THREAD

**Issue by SukMeWot** [Duet3D/RepRapFirmware#364]
In RRF RC2 when using stall guard as an endstop the S4 parameter behaves as per S3 in a multi stepper Z axis, 

Instead of each motor driving until it stalls the movement of all motors stops when the first motor stalls. Behaviour of S4 option is not as described.

Axis definition - M584 X0 Y1 Z2:3:4 E5 P3

This config line does not work as expected - M574 Z1 S4

> New endstop type S4 means use motor stall detection (like S3) but if there are multiple motors, stop each one individually as it stalls.

**Comment by T3P3** [comment]
please test this on the latest firmware . if it is still happening them please post a forum post about it.
