### ISSUE TITLE
Feature Request: Add Z probe thermal compensation curve with interpolation instead of thermal coefficient parameter.

### ISSUE THREAD

**Issue by boa-pe** [Duet3D/RepRapFirmware#366]
I would like to use inductive sensor for bed probing. It works fine in terms of homing and probing the bed. However it has some thermal drift (like most of inductive sensors).

Ideal situation (except internally compensated sensor) would be to define few points of the compensation curve. Linear compensation works good-ish, but not good enough.

Something like:
**G31 S20:30:50:70 C0.02:0.05:0.10:0.20 H2**

I did some tests for a few sensors and thermal drift is definitely not linear.

All of this concerns RRF3.0.

**Comment by dc42** [comment]
RRF already supports quadratic compensation. This should be sufficient.
