### ISSUE TITLE
Support Dwell (G4) in Laser mode.

### ISSUE THREAD

**Issue by LarsGBV** [Duet3D/RepRapFirmware#370]
Hi, I have build a diode laser cnc and I am having a little issue which I think 
is due to the diode having a small warm up time. 

So I would like to call a dwell with the laser on for 100ms but it seems to be impossible with the instruction set.

Is it possible somehow or might it be introduced at some point ?

My workaround for the moment is a short movement on the Z axis in my post processor
to simulate a dwell. A very short XY axis movement would also be possible I guess.

I would also be nice for when you want to turn on the laser, on low power, to focus it or similar,

**Comment by T3P3** [comment]
Please comment if this is still a requirement, how common are lasers that require a dwell before they come up to power an motion can start?

For the focus request there is another issues raised:
https://github.com/Duet3D/RepRapFirmware/issues/697

**Comment by ghawkesford** [comment]
Seems more than reasonable to me that G4 should be available in laser mode, can't understand why it should have been taken out, I use it in CNC mode for a similar thing when starting the spindle.

**Comment by T3P3** [comment]
AFAIK this issue is specifically about having a built in dwell, after the laser starts firing, before motion starts, built into the G1 motion command when ever the laser is started from "off"

A normal G4 command works in all mode on RRF.

**Comment by ghawkesford** [comment]
That's strange then, from LarsGBVs comments, but I do recall from the dim and distant past that there are things to do at the start of a laser cut, possibly more than just a dwell??  In any case, I would imagine that it's a post-processor issue.

**Comment by T3P3** [comment]
I think the comment makes sense as he is commanding a Z move as a work around (so start firing the laser, do a short Z move then start the desired motion). Anyway we need owners of these sorts of lasers to confirm the requirement.

**Comment by dc42** [comment]
I am not aware of any other controller firmware that supports this. Perhaps it can it be simulated by reducing acceleration?

**Comment by T3P3** [comment]
please reopen if still relevant
