### ISSUE TITLE
If doing a multi-axis "G1 H3" move, M500 does not save limits properly

### ISSUE THREAD

**Issue by eweilow** [Duet3D/RepRapFirmware#390]
I've been working on getting a self-levelling bed with three independent motors going lately, and have encountered an issue with using the `H3` parameter on `G1`. 

It seems as if something is going wrong when splitting the axes using `M584` and that `numVisibleAxes` in the source doesn't properly update.

The issue that I've run into is the following scenario:
```
G1 Z100 ; move Z to 100
M584 Z3 U4 V5 P5 ; split motors
G92 Z100 U100 V100 ; set coordinates, assume axes are equal

G91 ; relative coords
G1 H3 Z400 U400 V400 F600 ; Move axes until endstops are hit

M500 ; this should store the limits

M584 Z3:4:5 ; restore motors
```

The resulting `config-override.g` only outputs one of the axes, however:
```
M208 S0 Z<...> ; the exact Z value is not important
```

## A workaround
By doing a combined move first, and then individually checking each of the axes, the correct output can be achieved. This would look like the following:
```
G1 Z100 ; move Z to 100
M584 Z3 U4 V5 P5 ; split motors
G92 Z100 U100 V100 ; set coordinates, assume axes are equal

G91 ; relative coords
G1 H3 Z400 U400 V400 F600 ; Move axes and sense endstops

G1 Z-5 U-5 V-5 ; back off
G1 H3 Z10 F400 ; sense Z motor
G1 H3 U10 F400 ; sense U motor
G1 H3 V10 F400 ; sense V motor

M500 ; this should store the limits

M584 Z3:4:5 ; restore motors
```

The resulting `config-override.g` then does output all the tested axes:
```
M208 S0 Z<...> U<...> V<...> ; the exact values are not important
```

## Diagnostics and board info

The board is a `Duet 3 MB6HC 1.0` running `RRF 3.01-RC9`. 

<details>
<pre>
=== Diagnostics ===
RepRapFirmware for Duet 3 MB6HC version 3.01-RC9 running on Duet 3 MB6HC v0.6 or 1.0
Board ID: <board ID>
Used output buffers: 1 of 40 (12 max)
=== RTOS ===
Static ram: 154572
Dynamic ram: 163192 of which 208 recycled
Exception stack ram used: 536
Never used ram: 74708
Tasks: NETWORK(ready,2076) HEAT(blocked,1184) CanReceiv(suspended,3824) CanSender(suspended,1432) CanClock(blocked,1432) TMC(blocked,80) MAIN(running,2808) IDLE(ready,80)
Owned mutexes:
=== Platform ===
Last reset 00:55:45 ago, cause: power up
Last software reset at 2020-04-25 11:17, reason: User, spinning module LinuxInterface, available RAM 79556 bytes (slot 0)
Software reset code 0x0010 HFSR 0x00000000 CFSR 0x00000000 ICSR 0x0444a000 BFAR 0x00000000 SP 0xffffffff Task 0x4e49414d
Error status: 0
Free file entries: 10
SD card 0 not detected, interface speed: 37.5MBytes/sec
SD card longest block write time: 0.0ms, max retries 0
MCU temperature: min 33.9, current 37.9, max 38.2
Supply voltage: min 11.8, current 11.9, max 12.3, under voltage events: 0, over voltage events: 0, power good: yes
12V rail voltage: min 10.8, current 11.0, max 11.1, under voltage events: 0
Driver 0: standstill, reads 5111, writes 25 timeouts 0, SG min/max 0/307
Driver 1: standstill, reads 5111, writes 26 timeouts 0, SG min/max 0/298
Driver 2: standstill, reads 5122, writes 15 timeouts 0, SG min/max 0/0
Driver 3: standstill, reads 5096, writes 41 timeouts 0, SG min/max 0/714
Driver 4: standstill, reads 5091, writes 47 timeouts 0, SG min/max 0/702
Driver 5: standstill, reads 5091, writes 47 timeouts 0, SG min/max 0/731
Date/time: 2020-04-25 13:18:40
Slowest loop: 6.38ms; fastest: 0.14ms
=== Move ===
Hiccups: 0(0), FreeDm: 375, MinFreeDm: 372, MaxWait: 1749247ms
Bed compensation in use: none, comp offset 0.000
=== MainDDARing ===
Scheduled moves: 58, completed moves: 58, StepErrors: 0, LaErrors: 0, Underruns: 0, 0  CDDA state: -1
=== AuxDDARing ===
Scheduled moves: 0, completed moves: 0, StepErrors: 0, LaErrors: 0, Underruns: 0, 0  CDDA state: -1
=== Heat ===
Bed heaters = 0 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1, chamberHeaters = -1 -1 -1 -1
Heater 1 is on, I-accum = 0.0
=== GCodes ===
Segments left: 0
Movement lock held by null
HTTP* is ready with "M122" in state(s) 0 0 0 59 0 59, running macro
Telnet is idle in state(s) 0
File is idle in state(s) 0
USB is idle in state(s) 0
Aux is assembling a command in state(s) 0
Trigger* is idle in state(s) 0
Queue is idle in state(s) 0
LCD is idle in state(s) 0
SBC is idle in state(s) 0
Daemon* is idle in state(s) 0
Autopause is idle in state(s) 0
Code queue is empty.
=== Network ===
Slowest loop: 1.23ms; fastest: 0.01ms
Responder states: HTTP(0) HTTP(0) HTTP(0) HTTP(0) HTTP(0) HTTP(0) FTP(0) Telnet(0) Telnet(0)
HTTP sessions: 0 of 8
- Ethernet -
State: disabled
Error counts: 0 0 0 0 0
Socket states: 0 0 0 0 0 0 0 0
=== CAN ===
Messages sent 13333, longest wait 0ms for type 0
=== Linux interface ===
State: 0, failed transfers: 0
Last transfer: 17ms ago
RX/TX seq numbers: 41014/41015
SPI underruns 0, overruns 0
Number of disconnects: 0
Buffer RX/TX: 0/0-0
=== Duet Control Server ===
Duet Control Server v2.1.0.0
Code buffer space: 4096
Configured SPI speed: 8000000 Hz
Full transfers per second: 29.26
</pre>
</detail>

**Comment by chrishamm** [comment]
Please confirm that this problem is still present in v3.1.0.
