### ISSUE TITLE
Support Alligator board

### ISSUE THREAD

**Issue by lorenzing** [Duet3D/RepRapFirmware#396]
Hi,
can you add the support for alligator board r2 to your firmware like old release ( https://github.com/3Dartists/dc42-RepRapFirmware-Alligator ) ? 
In the configurator I don't find them.

Thank you so much
Lorenzo

**Comment by dc42** [comment]
I've reinstated the Alligator build in the v2.05.2 branch of CoreNG and fixed the build error in the dev branch of RepRapFirmware. I've put an untested Alligator firmware binary at https://www.dropbox.com/sh/mk3jlsoi6gyxd8q/AABbEvX2qb19McbRe6UvRmI9a?dl=0.

**Comment by lorenzing** [comment]
Thank you so much!
