### ISSUE TITLE
Modal/sticky commands

### ISSUE THREAD

**Issue by MariusSchiffer** [Duet3D/RepRapFirmware#399]
Other firmwares (like Smoothieboard AFAIK) support modal/sticky commands, i.e. a line without command (but with parameters) repeats the previous command (if it is defined as modal, for example G1).
Is this supported? It does not work for me on RRF2 and I cannot find any documentation on this.

This behaviour would save filesize especially for raster laser engraving.

Example:
G1 X0 Y20 S100
X2.4 Y20 S74
X3.2 Y20 S64

**Comment by dc42** [comment]
It's already supported in both RRF2 and RRF3 when RRF is configured in CNC mode using M453. In RRF3 this has been extended to laser mode (M453).
