### ISSUE TITLE
Paneldue 7i does not connect with duet.

### ISSUE THREAD

**Issue by austaquio32** [Duet3D/RepRapFirmware#402]
good morning, I have a duet2 wifi with a paneldue 7i, with the version of reprap 3.01 rc11 and the paneldue works correctly, when updating to version 3.1.1 the paneldue does not connect with duet, I have it connected with the 4-wire cable, that could be happening.
ps: if i go back to rc11 it works correctly again.

**Comment by T3P3** [comment]
Have you seen this in the Whats New file:

> All PanelDue users: the PanelDue connector (or IO_0 on Duet 3) is no longer dedicated to PanelDue, therefore if you connect a PanelDue to this port you must use the following command in config.g to enable it: M575 P1 S1 B57600. You can use baud rates other than 57600, however the IAP files all assume 57600 baud; therefore if you use another baud rate then PanelDue will not display firmware update progress.

https://github.com/Duet3D/RepRapFirmware/blob/v3-dev/WHATS_NEW_RRF3.md

**Comment by giostark** [comment]
Hi, have you already added this line?
Release note 3.1.0:
https://github.com/Duet3D/RepRapFirmware/blob/v3-dev/WHATS_NEW_RRF3.md
> All PanelDue users: the PanelDue connector (or IO_0 on Duet 3) is no longer dedicated to PanelDue, therefore if you connect a PanelDue to this port you must use the following command in config.g to enable it: M575 P1 S1 B57600. You can use baud rates other than 57600, however the IAP files all assume 57600 baud; therefore if you use another baud rate then PanelDue will not display firmware update progress.

**Comment by austaquio32** [comment]
That was the problem, that I did not stop reading the readme, sorry for the failure, thank you all.
