### ISSUE TITLE
no 'OK' response when G28 command is used. Firmware 3.1.1

### ISSUE THREAD

**Issue by zudy** [Duet3D/RepRapFirmware#409]
When using command G28 or G28 and axes (G28 X/Y/Z) there is no response from duet 'ok message'. Command was done fyzicaly succesfully. Same problem was in beta version until 3.1.0. Version 3.1.0 was correct and after upgrade by RPi to version 3.1.1 by command sudo apt-get update & sudo apt-get upgrade same problem appeared again.
![image](https://user-images.githubusercontent.com/5257083/83758187-eca56900-a671-11ea-995b-b01c1b15553f.png)

**Comment by T3P3** [comment]
this looks to be fixed in RRF 3.2 please can you check to see if it is now working for you:

![image](https://user-images.githubusercontent.com/1642947/108698339-ef940280-74fb-11eb-8ba1-8e2be61d1f98.png)
