### ISSUE TITLE
RRF Config Tool/DuetWifi Update

### ISSUE THREAD

**Issue by Boltz16** [Duet3D/RepRapFirmware#410]
I am not sure where to put this but I just updated my Duet 2 Wifi from 1.21 to 3.1.1 I used the RRF Config tool to update my config.g file and I ran into an issue with my Z-Probe. I was having issues with my BLTouch not triggering when sending the G30 command while trying to trouble shoot this issue I was reading over the RepRapFirmware 3 Overview and looking at the example M558 code for the Bltouch and the duet wifi and noticed that the M558 P9 C”zprobe.in" H5 F120 T6000 line was missing the “^” and that the 2 lines were in a different order.

RRF Config Tool Code
M950 S0 C"exp.heater3" ; create servo pin 0 for BLTouch
M558 P9 C"zprobe.in" H5 F120 T6000 ; set Z probe type to bltouch and the dive height + speeds

RepRapFirmware 3 Over View code
M558 P9 C"^zprobe.in" H5 F120 T3000 ; BLTouch connected to Z probe IN pin
M950 S0 C"exp.heater3" ; create servo/gpio 0 on heater 3 pin on expansion connector

Fixing the RRF Tool code to match the Overview code seems to have fixed the issues

**Comment by chrishamm** [comment]
Thanks for the report, I'll change the config tool to activate the pull-up on BLTouch input pins.

The correct repository for ConfigTool issues is [here](https://github.com/Duet3D/ConfigTool) though.
