### ISSUE TITLE
M106 Does not Default to P0 on Duet Wifi

### ISSUE THREAD

**Issue by creek52** [Duet3D/RepRapFirmware#411]
M106 does not default to P0 on Duet Wifi

M106: Fan On
Parameters
    Pnnn Fan number (optional, defaults to 0). (In RRF_3 relates to the fan number created by M950, NOT the fan pin number on the board)
    Snnn Fan speed (0 to 255 or 0.0 to 1.0))

I have to manually search for M106 commands in gcode files and add P0 to lines.
My software (Symplify) does not allow any method to add a P0 to M106 command.
M106 S127 does not work.
M106 P0 S127 will work.

;config.g
;define fan
M950 F0 C"fan0" Q100   ;set fan 0 (filament cooling)
M106 P0 S0 H-1 B0.2 C"Filament"  ; fan off

**Comment by dc42** [comment]
Please use the duet3d forum for support.
