### ISSUE TITLE
Suggestion: implement disconnect parameter in rr_xxxxx calls

### ISSUE THREAD

**Issue by Oliv4945** [Duet3D/RepRapFirmware#413]
Hi,

It would be helpful to create script or integration in others tools if a parameter `disconnect` could be passed in the `rr_xxxxx` urls:
`GET http://${duet_hostname}/rr_status?type=3&disconnect=true` so the integration does not have to create another call to `rr_disconnect` after.

Thank you :)

**Comment by chrishamm** [comment]
`rr_status` is deprecated and I don't think this is a clean approach. `rr_connect` is always needed in case a password is set and if you use the forthcoming v3.5-b4, it will be possible to create multiple HTTP sessions per IP address identified using a single key (see updated HTTP docs about rr_connect). All HTTP sessions time out automatically after 8s of inactivity as well.

Hence I am closing this.
