### ISSUE TITLE
[Feature Request] Wipe option for a firmware retract

### ISSUE THREAD

**Issue by mkudzia84** [Duet3D/RepRapFirmware#416]
Hello,

Would it be possible to implement a feature to add wipe behaviour to the firmware retract G code?

Mxxx command that specifies the wipe parameters [max wipe distance, wipe move speed, enabled/disabled]

If this would be enabled when firmware retraction is triggered the tool would perform the wipe and then retract
In order to do so; when the wipe is enabled
The firmeware would have to maintain a backlog of moves which distances adds up to the max wipe distance [or less when not moves are not long enough - only moves with extrusions would add up]

**Comment by T3P3** [comment]
I can see an issue with this in determining which direction to do the wipe. Slicer's have more information about the whole print, the firmware does not have the same amount of information so determining a correct direction for wipe from (e.g.) the direction of previous print moves) would not necessarily result in a good wipe direction.

**Comment by T3P3** [comment]
Wipe should be handled by the slicer as it depends on the part geometry and the slicing path.
