### ISSUE TITLE
iap4e.bin needs to be easier for new users to find

### ISSUE THREAD

**Issue by jschall** [Duet3D/RepRapFirmware#422]

**Comment by bernhardberger** [comment]
+1

**Comment by T3P3** [comment]
The iap file is included in the firmware zip for each stable release, at least ti has been for the last few stable releases. Is this now sufficient?

**Comment by Aquilux** [comment]
Following firmware update (without web access) steps and when prompted deleted my .bin files. Now my duet2 is saying " 'iap4e.bin' not found" and I can't find that file anywhere in the 3.0.0 or latest firmware.

**Comment by dc42** [comment]
iap4e.bin is used only by older firmware versions. I think it should be in the .zip file in the 3.0 release.
