### ISSUE TITLE
Minor spelling mistake

### ISSUE THREAD

**Issue by LeavOA** [Duet3D/RepRapFirmware#425]
In "reset heater fault" dialog:
- Currently: Phsical
- Should be: Physical

![image](https://user-images.githubusercontent.com/14206460/93134547-92d92400-f6e1-11ea-9e19-f1349b16b68f.png)

**Comment by dc42** [comment]
Thanks for pointing this out. It's actually an error in DWC not in RRF. I will pass it on.
