### ISSUE TITLE
fan2 always on

### ISSUE THREAD

**Issue by LichtiMC** [Duet3D/RepRapFirmware#426]
Hey, 

after some time I updated my firmware to 3.2-beta1 and since then my "fan2" pin is always on at the start of the RepRapFirmware.
This probably would'nt be a problem if a fan had been connected, but I have a laser connected.

With only `M950 F2 C"nil"` command there is no change in this behaviour, but I managed to switch it off instantly after start with the command `M950 P0 C"fan2"`.

But I'd rather have it being switched off from the beginning as it was before the update for security reasons.

Do you know what suddenly causes this behaviour? Should'nt be all pins switched off by default?

Thanks

**Comment by dc42** [comment]
Please use the forum at https://forum.duet3d.com/ for support.
