### ISSUE TITLE
Error: Attempting to extrude with no tool selected

### ISSUE THREAD

**Issue by theshabobo** [Duet3D/RepRapFirmware#427]
**Hardware** info:**
Printer Base: Anycubic Predator
Mainboard: Duet 2 WIFI
Board Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.1.1 (2020-05-19b2)
Screen: Paneldue 7i
Screen Firmware: Version 3.2-RC1

**Issue:**

While trying to print a file I get this error:
Error: Attempting to extrude with no tool selected.

This happens occasional/randomly at different positions/times during the print.

This is not a "T0 in the gcode" problem.
To replicated I always used the same file, started the printer from off and did home the axes and bed level before starting the print.

What I found so far:
This happens during any file created by any slicer.

**Comment by dc42** [comment]
Please use the forum at https://forum.duet3d.com/ for support.
