### ISSUE TITLE
[Feature Request] Retraction distance based on time between retraction and extruding

### ISSUE THREAD

**Issue by CabalSoul** [Duet3D/RepRapFirmware#429]
I'm struggling wiht retraction settings when i have long travel moves. If i dial it in for small parts they work great but for bigger parts, or parts which are separated by a larger distance, it my be unsufficient because of the longer travel distance. I can remedy it to an extent with higher travel speeds, but i get a somewhat bigger risk of layer shifts due to high speed collisions with blobs or zits.
My suggestion is  to set a minimum retraction distance and a maximum retraction distance based on the time passed between the retraction and the next extruding move and scale it linearily between min/max time constraints.

**Comment by T3P3** [comment]
Best to use the required retraction distance for the longest moves.

Please open a discussion on the forum if this is still a requirement.
