### ISSUE TITLE
CoreXZ kinematics should not assume a 3:1 reduction unless specifically configured to do so. 

### ISSUE THREAD

**Issue by christophmuellerorg** [Duet3D/RepRapFirmware#430]
I am aware that the first CoreXZ design used a 3:1 reduction for Z, however the reduction [is not necessary](https://forum.duet3d.com/topic/18936/voron-switchwire-corexz) for a coreXZ design. Further, the 3:1 factor is [not documented](https://duet3d.dozuki.com/Wiki/Gcode#Section_M669_Set_kinematics_type_and_kinematics_parameters) and comes as a surprise to the user if their machine is not following the old 3:1 design.

Suggested solution: assume 1:1 and add an example configuration for 3:1 designs using the matrix notation to the documentation. Alternatively rename the current configuration CoreX3Z and treat CoreXZ with the same 1:1 assumption as CoreXY. When keeping the M669 code K2 for CoreX3Z and giving normal CoreXZ a new K number this change would have the benefit not to break anyone’s configuration.

**Comment by dc42** [comment]
I have updated the documentation for M669.
