### ISSUE TITLE
Duet 3 rrf 3.2.x + SBC: no resurrect.g is written

### ISSUE THREAD

**Issue by MartenPothoven** [Duet3D/RepRapFirmware#432]
(Duet 3 rrf 3.2.x + SBC) No resurrect.g file is written when pause is pressed.
But same Duet 3 board in stand alone mode with same config.g, everything works fine.

Power loss M911 also does not work with sbc but it does works fine in stand alone mode.
Has it to do with sudo rights (permissions) on the Raspberry Pi ?????  HELP

**Comment by T3P3** [comment]
This is as it is a DSF issue rather than RRF. See:
#https://github.com/Duet3D/DuetSoftwareFramework/issues/55
