### ISSUE TITLE
Duet 2 Wifi crashed and reset upon unloading filament

### ISSUE THREAD

**Issue by natthapolvanasrivilai** [Duet3D/RepRapFirmware#433]
The release 3.2beta2 seems to have a problem when running M702 or unloading filament.
I've tried uncommenting the gcodes inside the macro, but that didn't help.

Duet crash and reset itself immediately after the filament unload macro finished executed.

**Comment by afkfurby** [comment]
can confirm this.

**Comment by dc42** [comment]
Please post the M122 report after an uncommanded reset.

**Comment by natthapolvanasrivilai** [comment]
I've reverted back to 3.1.1, so I can't collect the report now. There is a print going on at the moment. Maybe someone with the same problem can provide their result.

**Comment by dc42** [comment]
I have identified the issue and fixed it. The fix will be in the next beta release.
