### ISSUE TITLE
acces denied 3.2.0-beta2

### ISSUE THREAD

**Issue by touchthebitum** [Duet3D/RepRapFirmware#434]
Hello
I just updated my firmware and I get this when I want to upload or modify my config.g file :
Operation failed (Reason: Access to the path '/opt/dsf/sd/sys/DuetWiFiServer-1.24beta2.bin' is denied.)
Here is the general info :
Board: Duet 3 MB6HC (MB6HC)
DSF Version: 3.2.0-beta2
Firmware: RepRapFirmware for Duet 3 MB6HC 3.2-beta2 (2020-10-05b2)
I made update and upgrade on my Raspberry Pi too.
Where am I wrong ?
Thanks

**Comment by T3P3** [comment]
https://forum.duet3d.com/topic/19053/new-firmware-bundle-3-2beta2/47?_=1603195518200
