### ISSUE TITLE
Abort command in load.g or unload.g filament macros changes filament, as it was correctly loaded/unloaded

### ISSUE THREAD

**Issue by michele-bertoni** [Duet3D/RepRapFirmware#437]
If an abort command is called when loading or unloading a filament (both with M701 or M702 and with the Duet Web Control), Duet will then change the filament name of the associated tool, as the filament was correctly loaded or unloaded. A very strange behavior happens, instead, when an error (such as G0/G1: insufficient axes homed) is thrown: in this case the filament name is not changed. The problem happens both if the abort command is inside load.g/unload.g file and if it is inside a nested macro called by load.g/unload.g.

**Comment by zombiRon** [comment]
forget abort, you can't even change filament without a reset

**Comment by michele-bertoni** [comment]
> forget abort, you can't even change filament without it resetting

You mean the error present in latest beta release? It has already been fixed for the next beta release

**Comment by zombiRon** [comment]
Yes, so how are you testing this without it resetting?

**Comment by michele-bertoni** [comment]
> Yes, so how are you testing this without it resetting?

I'm using latest working release and, since I haven't found anyone reporting this bug, I assumed that it wasn't fixed yet

**Comment by zombiRon** [comment]
you're running 3.1.1?

**Comment by michele-bertoni** [comment]
Yes, 3.1.1, last stable release

**Comment by michele-bertoni** [comment]
I found out that if the tool is deselected (with T-1) at the time the load/unload macro ends, the filament won't change its state. So, if you do T-1 before calling abort, it works fine.

**Comment by skezo** [comment]
This issue is present in `release 3.4.5`.
If you run `abort "Cancel load"` inside `/filaments/<filament>/load.g` or inside a submacro of `load.g` the Filament will change state.

This also happens if your macro contains `M291` command with `S3`. If the user presses "Cancel" the filament will change to the new state.

EDIT
Added some more info here: https://forum.duet3d.com/topic/32139/how-to-cancel-loading-unloading-of-filament

**Comment by T3P3** [comment]
Closed as M99 is the correct approach - see the forum thread.

abort commands are not supported at this point in system macros.
