### ISSUE TITLE
Extend M36 by a flag for thumbnails

### ISSUE THREAD

**Issue by wilriker** [Duet3D/RepRapFirmware#439]
In order to implement https://github.com/Duet3D/PanelDueFirmware/issues/77 it is necessary to have a means of fetching information if a thumbnail is included in a GCode file. This is done e.g. by PrusaSlicer by including a base64 encoded PNG thumbnail of the model. There is also the [UFP format](https://plugins.octoprint.org/plugins/UltimakerFormatPackage/) that bundles the GCode and a separate PNG in a ZIP file.
A new flag containing this information could be added to `M36`.

Additionally a new command (`M36.1`?) to return this thumbnail is required. In case of the UFP format RepRapFirmware would need to base64-encode the image.

**Comment by dc42** [comment]
Implemented in RRF 3.4.
