### ISSUE TITLE
In marlin compatibility, missing' \n' after "OK" response when M20 command is used.

### ISSUE THREAD

**Issue by Subcircuit** [Duet3D/RepRapFirmware#453]
In marlin compatibility, **missing '\n'** after "OK" response when M20 command is used.   
FIRMWARE_VERSION: 3.1.1 
```
    Begin file list 
    text.gcode 
    End file list 
    ok (here missing '\n') 
```

**Comment by Subcircuit** [comment]
Sending M20 from panelDUE found the problem, I tested the usb port and it is working.

**Comment by dc42** [comment]
PanelDue does not require a terminating \n so it is omitted from most responses. If you put the aux port into raw mode using M575 (only available in recent RRF3 versions) then the \n should be present.

**Comment by Subcircuit** [comment]
@dc42 Sorry, my description not clear.  
I'm using M575 P1 S2 B115200 with marlin compatibility mode and send m20  without ’\n‘ response at the end , but other gcodes (m104, m106, m119, m105, m21 etc.) do have ‘\n’!  
This prevents me from parsing the M20 response correctly.

**Comment by dc42** [comment]
Please try RepRapFirmware 3.2beta4.1. The code to generate responses was changed in that version, so it may be fixed already.

**Comment by Subcircuit** [comment]
Hi, I tested 3.2beta4, 3.2beta4.1 and still have the problem.

**Comment by Subcircuit** [comment]
@dc42  
Before that I was testing on Duet 2 wifi board.
Today I tested Duet3 6HC firmware version 3.1.1 , there is no such problem. (All test environments are the same except for the board).

**Comment by dc42** [comment]
Can you try firmware 3.2RC1 on a Duet WiFi?

**Comment by Subcircuit** [comment]
Oh great, it's working. Thank u
