### ISSUE TITLE
Enable auto-sleep makes dwc freezes at the end of the print

### ISSUE THREAD

**Issue by delious87** [Duet3D/RepRapFirmware#457]
You cant send commands and there is no real time updates after the print finishes with auto-sleep enabled.
Refresh of the page helps
sleep.g contains M81 S1
If you send M81 S1 by the console it works as auto-sleep should and you can close browser.

Board: Duet 2 WiFi (2WiFi)
Duet Web Control 3.2.0-beta4
Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.2-beta4 (2020-11-26)
Duet WiFi Server Version: 1.25beta0

The same behavior was on previous firmware

**Comment by T3P3** [comment]
please pen a forum discussion about this if it is still an issue in RRF 3.4.5
