### ISSUE TITLE
Declaring of multiple heaters for one tool.

### ISSUE THREAD

**Issue by G4Cab** [Duet3D/RepRapFirmware#459]
I have a 3in1 mixing hotend which uses two heater cartridges.
I have connect one cartridge to H0 and one to H1.
How can i declare it to be used simultaneously?

I tried:
   M950 H1 C"e0heat+e1heat" T1
but that doesn't do the trick. So how is the way to do it?

**Comment by dc42** [comment]
Two ways:
1. In RRF 3.4 you can use multiple outputs per heater.
2. Otherwise you can declare that a tool uses multiple heaters, e.g. M563 T0 H1:2
