### ISSUE TITLE
v3.2 Compensation and Mesh Leveling

### ISSUE THREAD

**Issue by carloperatoner** [Duet3D/RepRapFirmware#463]
I upgraded one of my Rostock Max V2 machines to Version 3.2
Firmware 3.2
Duet Web Control 3.2
PanelDue 3.2.7
Love the ease of the upgrade process.

After my initial upgrade, I decided to recalibrate my printer and run a mesh.     I run these several times to make sure I get the best result.   With the new firmware, I do not get a confirmation dialog on the screen or in the console after the first successful run of the  "Delta Calibration" or "Mesh Compensation".   If I reboot the controller it will work the first time.

Anyone experiencing the same issue?

I am running a cyclops head dual extrusion.  Here is my config.g file:

G90                                                                  ; Send absolute coordinates...
M83                                                                 ; ...but relative extruder moves
 
M665 L300.000:300.000:300.000 R142.509      ; Set delta radius, diagonal rod length
M665 H352.488 B140.0 X0.170 Y0.257 Z0.000
M666 X0.799 Y-1.254 Z0.455 A0.00 B0.00       ; Put your endstop adjustments here, or let auto calibration find them                                                                     
M579 X1.02454 Y1.02640 Z0.98039                ; Scaling Factors
 
; Network
M550 P"3dConsole 2"                                     ; Set machine name
M552 P10.10.10.43 S1                                     ; Enable network and set IP address
M553 P255.255.255.0                                      ; Set netmask
M554 P10.10.10.1                                            ; Set gateway
M555 P2
M586 P0 S1                                                      ; Enable HTTP
M586 P1 S0                                                      ; Disable FTP
M586 P2 S0                                                      ; Disable Telnet

M575 P1 S1 B57600					; Setup PanelDue

M584 X0 Y1 Z2 E3:4                                        ; set drive mapping

; Drives
M569 P0 S0                                                      ; Physical drive 0 goes backwards X axis
M569 P1 S1                                                      ; Physical drive 1 goes forwards Y axis
M569 P2 S0                                                      ; Physical drive 2 goes backwards Z axis

M569 P3 S0                                                      ; Physical drive 3 goes backwards E0
M569 P4 S0                                                      ; Physical drive 4 goes backwards E1

M92 X160 Y160 Z160 E182:182                        ; Set steps per mm
M350 X16 Y16 Z16 E16:16 I1                            ; Configure microstepping with interpolation
                            
M566 X500 Y500 Z500 E2000:2000                  ; Set maximum instantaneous speed changes (mm/min)
M203 X15000 Y15000 Z15000 E15000:15000 I800   ; Set maximum speeds (mm/min)
M201 X3400 Y3400 Z3400 E5000:5000            ; Set accelerations (mm/s^2)
M906 X1400 Y1400 Z1400 E1200:1200 I50      ; Set motor currents (mA) and motor idle factor in per cent
M84 S30                                                           ; Set idle timeout

; Axis Limits
M208 Z0 S1                                                      ; Set minimum Z

; Endstops
M574 X2 S1 P"xstop"                                        ; configure active-high endstop for low end on X via pin xstop
M574 Y2 S1 P"ystop"                                        ; configure active-high endstop for low end on Y via pin ystop
M574 Z2 S1 P"zstop"                                        ; configure active-high endstop for low end on Z via pin zstop

M591 D0 P2 S1 C"e0stop"        		          ; Set Runout Sensor Extruder 0
M591 D1 P2 S1 C"e1stop"				  ; Set Runout Sensor Extruder 1

; Z-Probe

M558 P8 C"!zprobe.in" H3 F120 T3000 A1 R.4  ; Set Z probe type to switch and the dive height + speeds
G31 P1000 X0 Y0 Z-0.5308                                ; Set Z probe trigger value, offset and trigger height
M557 R120 S20						  ; Define mesh grid
 

; Heaters

M307 H0 B0 S1.00                                             ; Disable bang-bang mode for the bed heater and set PWM limit
M308 S0 P"bed_temp" y"thermistor" T100000 B4925   ; Set thermistor + ADC parameters for bed

M308 S1 P"e0_temp" y"thermistor" T100000 B3950     ; Set thermistor + ADC parameters for extruder0
;M308 S2 P"e1_temp" y"thermistor" T100000 B3950     ; Set thermistor + ADC parameters for extruder1

M308 S3 Y"mcu-temp" A"MCU"                        ; configure sensor 3 as thermistor for MCU

M950 H0 C"bed_heat" T0

M950 H1 C"e0_heat" T1
M950 H2 C"e1_heat" T2

M143 H0 T0 S120 A0                                         ; Set temperature limit for bed heater 0 to 120C
M143 H1 T1 S275 A0					   ; Set temperature limit for extruder 0 heater 0 to 275C
M143 H2 T2 S275 A0					   ; Set temperature limit for extruder 1 heater 0 to 275C

; Fans
M950 F0 C"fan0" Q500                                       ; CPU Fan
M950 F1 C"fan1" Q500					   ; Peek Fan
M950 F2 C"fan2" Q500		                           ; Work Fan

M950 F3 C"exp.heater3" Q500                 	   ; LED Ring
;M950 F4 C"exp.heater4" Q500			   ; Empty
;M950 F5 C"exp.heater5" Q500	                   ; Empty
;M950 F6 C"exp.heater6" Q500                	   ; Empty

M106 P0 S0.25 H100:101:102 T45:65                 ; Set BoardFan value, PWM signal inversion and frequency. Thermostatic control is turned on
M106 P1 S1 H-1                                                  ; Set Peek value, PWM signal inversion and frequency. Thermostatic control is turned off
M106 P2 S0 H-1                                                  ; Set Work value, PWM signal inversion and frequency. Thermostatic control is turned off
M106 P3 S60 H-1			                    	    ; Set LED value, PWM signal inversion and frequency. Thermostatic control is turned off

; Bed
M140 H0 S20 R50 				                    ; Set bed temperature to 20 and standby to 50

; Tools
M563 P0 S"Primary" D0 H1                                 ; Define tool 0
G10 P0 X0 Y0 Z0                                                 ; Set tool 0 axis offsets
G10 P0 S20 R200                                                 ; Set initial tool 0 active and standby temperatures to 200C

;M563 P1 S"Secondary" D1 H2                            ; Define tool 1  (enable for chimera)
M563 P1 S"Secondary" D1 H1                            ; Define tool 1  (enable for cyclops)
G10 P1 X0 Y0 Z0                                                 ; Set tool 1 axis offsets
G10 P1 S20 R200                                                 ; Set initial tool 1 active and standby temperatures to 200C

; Custom settings are not configured
M307 H0 A102.0 C896.7 D3.6 S1.00 V13.8 B0    ; Set Bed PID setting
M307 H1 A396.4 C125.4 D5.7 S1.00 V13.9 B0    ; Set Extruder 0 PID setting (enable for chimera)												
;M307 H2 A575.3 C180.5 D3.5 S1.00 V13.8 B0   ; Set Extruder 1 PID setting (enable for chimera)

M501				                                   ; Read EPROM

T0
G28

**Comment by T3P3** [comment]
Please use the forum for configuration support.
