### ISSUE TITLE
Layer chart for print jobs that include multiple items printed one at a time stops at the top layer of the first item

### ISSUE THREAD

**Issue by GoremanX** [Duet3D/RepRapFirmware#467]
When setting up a job that includes multiple items, and using Cura's "One at a time" option for the print mode, the layer chart in DWC only tracks the status of layers up to the top of the first item. Ideally (assuming a first object with 30 layers), layer 1 of the next object should be considered layer 31, etc, to at least have the chart be representative of the overall print job.

**Comment by T3P3** [comment]
This needs further thought on how layers vs Z height are reported by RRF and then used by DWC

**Comment by dc42** [comment]
RRF no longer tries to calculate the layer height, it just reports any layer heights that the GCode file being printed provides in the comments. So any remaining work on displaying layer number needs to be done in DWC. Layer number should not be used as an indication of remaining print time.
