### ISSUE TITLE
Feature request: Controlling stepper motor with M106 fan control.

### ISSUE THREAD

**Issue by astorun** [Duet3D/RepRapFirmware#483]
Hi all,

I already posted on duet3d forum but copying here as well.

I would like to use a regular air compressor for part cooling.
To accomplish that I will connect a stepper motor to an air regulator via shaft coupling.

So I can control the air regulator by turning stepper motor via gcode. It is possible to use a post processing script to convert M106 command to axis command like M106 S125 to G0 A125 to move the stepper to that exact position.

Downside is it will act as an axis rather than fan control on duet web control and I assume it cannot be moved or changed during printing. There is also post processing script involved on slicer software.

Is it possible to add additional subcommand(s) feature to M106 to specify an axis to control and move it rather than PWM control.

Example (K subcommand)

M106 KA P1 ; set P1 to A axis to be controlled via M106

Then it can be controlled like this

M106 P1 S127 ; set A axis to 127mm
or
M106 S127

So additional K subcommand can be used to define an axis as fan and it can be controlled via P subcommand between 0-255

Axis step, travel limitation and acceleration can be set via config.g as regular way with M92, M208 and M201.

Max travel can be limited to max value of 0 to 255 like regular PWM with M208 and step count can be determined for travel distance.

That will be very neat solution.

**Comment by T3P3** [comment]
Related Forum thread:

https://forum.duet3d.com/topic/21782/feature-request-controlling-stepper-motor-with-m106?_=1683205832674

This can be achieved using deamon.g as outlined in the thread:

```
if move.axes[3].homed
  G90
  G1 A{fans[0].requestedValue * 255}
```
