### ISSUE TITLE
Case-sensitivity for conditional gcode

### ISSUE THREAD

**Issue by wildblue** [Duet3D/RepRapFirmware#488]
On the panelDuet ist quite hard to Type Only in lowercase. On a Smartphone its the same, as every First Character gets Sometimes uppercased.

Echo Global.posx

Would Return an Error on the panelDue and in console.

Please remove the case-sensitivity there, as other gcodes Work in either was.

3.3beta2 duet2wifi

**Comment by dc42** [comment]
I do on intend to make variables etc. case insensitive.
