### ISSUE TITLE
M585 does Not Update laststopheight

### ISSUE THREAD

**Issue by wildblue** [Duet3D/RepRapFirmware#490]
When using m585 the field LastStopHeight does Not get updated

3.3beta2 duet2wifi

**Comment by dc42** [comment]
This needs some thought, because the stop position is only a height if probing was in the Z direction. Also, as the defined function of M585 is to set the tool offset, the stop height is in essence defined by the M585 axis parameter, and the tool offset is adjusted to give that stop height.

**Comment by wildblue** [comment]
With conditional gcode we are now able to iterate over single commands like M585. If the result of a single probing action (this is also valid for G30; consider multiple probing with one command as well) is Not accessible via OM, the whole Idea behind this awesome approach would get a hard hit.

**Comment by dc42** [comment]
I think you can already work out the M585 stop height from the new tool offset.

**Comment by wildblue** [comment]
Regardless of what M585 can be used for, it is using a probe which has a set of variables describing its status which includes also the laststopheight. What is happening to M585's variables is secondary here.

For what does the variable laststopheight else exists? Get rid of it, if it is not updated by a sensor probe.
Or maybe even better: just implement the missing code for M585? You decide!

**Comment by T3P3** [comment]
Please open a discussion on the forum for this if it does not already exist (if it does link it from there).

**Comment by T3P3** [comment]
please reopen if still relevant
