### ISSUE TITLE
Working with global variables not working correctly on panelDue

### ISSUE THREAD

**Issue by wildblue** [Duet3D/RepRapFirmware#493]
If you type
"echo global.variablename"
on PanelDue you get the response
"unknown command" and the content of the variable is displayed in a second row.

3.3b2, Duet2wifi, panelDue v3 5"

**Comment by dc42** [comment]
I can't reproduce this. Using a firmware build a little later than 3.3beta2 and PanelDueFirmware 3.2.11, I don't get "unknown command".
