### ISSUE TITLE
Temperature and tool changes on mixing hot-ends Locking up the engine.

### ISSUE THREAD

**Issue by nanoplane** [Duet3D/RepRapFirmware#497]
So, this seems weird, but the system can lock up when supporting multiple tools on a mixing hot end (all tools tied to the same heater/fan combination)

Example:
; Note: code generated by SuperSlicer..

(T0 and T1 already created, both on H1 F1)
Both have active and standby temps of 0

; SuperSlicer generates
T0
G10 P1 R240
G10 P1 S240

; Custom Start GCode )
G10 P0 S240
M116
T0
;print some stuff
T1
G10 P1 S240
M116

And... it's locked up.. only solution is a switch (power) reboot.

**Comment by T3P3** [comment]
Please check if you can reproduce this issue in RRF 3.4.5, if you can the re-open the issue.
