### ISSUE TITLE
M80 not working went sent from Gcode file 

### ISSUE THREAD

**Issue by broncosis** [Duet3D/RepRapFirmware#498]
I dove on the new beta for the variables to make start code more uniform think I may have found a bug 

But as I use ATX power switching I noticed M80 is not launching from the job file or the Macro file 
M81 apeears to be working from macro files 
and I can send M80 on the console and it works as well at the button on the dash board

**Comment by broncosis** [comment]
Running on a duet2 wifi    

[config.txt](https://github.com/Duet3D/RepRapFirmware/files/6176969/config.txt)
attached is my config

**Comment by broncosis** [comment]
OK seems to be fine called from a Macro run from the webUI but not when the Macro is called from a job file
also works from the Job File 
I can work around this but now but still worth noting

**Comment by dc42** [comment]
Please re-test using RRF 3.4.0.

**Comment by broncosis** [comment]
I just updated sorry for the slow response I will try this thanks
