### ISSUE TITLE
When a new (second) probe via M558 is created, a probe offset of 0.7 is asumed

### ISSUE THREAD

**Issue by wildblue** [Duet3D/RepRapFirmware#500]
even no offset was specified in the M558 command.

I started with only one probe configured, and added the second probe in the console:

21.3.2021, 14:54:57	G31K1
Z probe 1: current reading 0, threshold 500, trigger height 0.700, offsets X0.0 Y0.0
21.3.2021, 14:54:48	M558 K1 P8 C"!e0stop" F300:300 T2000 H5
21.3.2021, 14:54:40	G31K1
Error: G31: Invalid Z probe index
21.3.2021, 14:54:20	Connection established

3.3b2, duet2wifi

**Comment by dc42** [comment]
There has to be a default trigger height for when the user doesn't provide one, and it happens to be 0.7 for historical reasons. Whatever default we choose will only be correct for a very small number of users.
