### ISSUE TITLE
When using multiple  G1 commands with H1 parameter, the movement is not continuous

### ISSUE THREAD

**Issue by wildblue** [Duet3D/RepRapFirmware#501]
Driving an axis using multiple G1 commands with different speeds result in "one" very smooth movement. You can not tell whether the motion was created by several movement-commands.
-> try for yourself:
G1 Z50 F1000
G1 Z100 F600

When it is importamt to stop the motion at the axis endstop-switch, you add the parameter H1 to your G1 command. This two commands now result in a very different behaviour of the movement, as it consists of two separate movements with a ramp-down to zero velocity in between.

-> try for yourself:
G1 Z50 F1000 H1
G1 Z100 F600 H1

This does not result in one smooth motion as expected.

33b2 duet2wifi

**Comment by dc42** [comment]
This is intentional. When using the H1 parameter, the motion may be terminated by an endstop being triggered; so at the end of the G1 H1 command the firmware needs to stop and recalculate the machine position before any further motion commands can be processed.
