### ISSUE TITLE
Duet2wifi Not responding after movement when power is off

### ISSUE THREAD

**Issue by wildblue** [Duet3D/RepRapFirmware#502]
Try the following (I did all this on my panelduet)
<Reboot>
M81; Power is off at this point

G92 Z0; Set z-axis position to zero
G1 G10;
<You are notified that there is no power>
M80; Set power on
<Power on now>
G1 G10; does nothing
G92 Z0;
G1 G10; does nothing
G28; Home printer
<X and Y are homed, printer halts>

When running M81, M80 and G28 again, the z-axis will Work again.

33b2, duet2wifi, panelduet5v3
Same in DWC

**Comment by T3P3** [comment]
`G1 G10;`

That is not valid axis assignment

Please use the Duet3D forum for support.
