### ISSUE TITLE
Login at forum.duet3d.com not possible due to exessive load

### ISSUE THREAD

**Issue by wildblue** [Duet3D/RepRapFirmware#503]
I know, this is not the right place, but ti know there is at least one entity here to fix this. Also the forum does not let me log in, to report this issue there. :-)

Android 10, Chrome Beta 90.0.44.30.30

**Comment by T3P3** [comment]
Yep, we are having some load issues. Working on it!

**Comment by T3P3** [comment]
hopefully the new version and other server changes have sorted this.
