### ISSUE TITLE
Duet 3 mini 5+ sensorless homing not working

### ISSUE THREAD

**Issue by delious87** [Duet3D/RepRapFirmware#504]
Trying motors 0.9 and 1.8 degrees, a lot of variations of speed, sensitivity, homing speed, stealthchop adjustment. Latest version of the firmwares ( Duet Web Control 3.3.0-b2 RepRapFirmware for Duet 3 Mini 5+ 3.2-beta3.2+1 (2020-11-15)
Duet WiFi Server Version: 1.25). The motors continue moving after stall even with M915 S-63 parameter. Everything works great on duet 2 wifi board. CoreXY 3d printer.

**Comment by dc42** [comment]
Please use the forum for support.
