### ISSUE TITLE
3.2.2 Reset after M303

### ISSUE THREAD

**Issue by vcapra1** [Duet3D/RepRapFirmware#506]
Whenever I try to run heater tuning with M303, just as it's about to be complete, the printer resets and the tuning doesn't finish.  Then if I run M303 it just says no heater has been tuned since startup.  There's no failure message in the log or anything, it just resets.

![image](https://user-images.githubusercontent.com/23411890/114564630-7c2a8980-9c3e-11eb-8e80-3241cd225ca1.png)

Board: Duet 2 Ethernet (2Ethernet)
Firmware: RepRapFirmware for Duet 2 WiFi/Ethernet 3.2.2 (2021-02-11)

**Comment by dc42** [comment]
Please report this on the forum and post a M122 report taken after the printer has reset.
