### ISSUE TITLE
RRF3.3b3 on Duet2Wifi thermocouple sensor issue: "Error: M308: string too long"

### ISSUE THREAD

**Issue by mctaylor82** [Duet3D/RepRapFirmware#509]
Duet2Wifi was running RRF3.2.2 and bed heater working normally. After update to 3.3b3 the bed heat sensor is throwing an error:

> M308 S0 P"spi.cs2" Y"thermocouple-max31856" T"K" F60 A"Bed"
> Error: M308: string too long

Issue also appears to be present in 3.3b2.

**Comment by dc42** [comment]
Thanks for reporting this. Will be fixed in next 3.3beta or RC.
