### ISSUE TITLE
Code Formatting Conventions

### ISSUE THREAD

**Issue by tobbelobb** [Duet3D/RepRapFirmware#511]
How are formatting conventions are enforced in this repo?

I've tried default clang-format options, and default eclipse formatting, but they both change my file (HangprinterKinematics.cpp) too significantly.

**Comment by dc42** [comment]
I edited the Eclipse formatting conventions. However, I never reformat the whole file because Eclipse has sometimes got it wrong in the past.

**Comment by tobbelobb** [comment]
Ok, I'll hand-format as good as I can then, no problem.
