### ISSUE TITLE
Re-setting plane for arc moves when starting/restarting a job to XY / G17

### ISSUE THREAD

**Issue by derd3** [Duet3D/RepRapFirmware#514]
feature request:

If a job is run where a G18/19 command is used for a G2/3 command like "G18 G2 X0 Y0 ...."
the next job takes over the last plane for new arc-moves that was set in the previous job. 
I think after a job has ended or is canceled, all moves should again be made in the XY plane by default, without the need for explicitly setting it.

**Comment by dc42** [comment]
In 3.3RC2 the plane when starting a job is now set to the XY plane. All GCode input channels have independent plane selection, so no additional action is needed when cancelling a job.
