### ISSUE TITLE
Add inversion for M80 and M81 commands

### ISSUE THREAD

**Issue by cyrax72** [Duet3D/RepRapFirmware#518]
Good day. It would be very nice to be able to invert the behavior of the M81 and M80 commands. the fact is that most of Mean Well and others power supplies, as well as solid-state relays, do not have the same power control as ATX, but the opposite.

**Comment by T3P3** [comment]
Example power supply's data sheet: https://www.meanwell.com/webapp/product/search.aspx?prod=EPP-300

In this example the  PS-ON feature is the inverse of what M80 and M81 currently do. From their spec: Power on: PS-ON = "Hi" or " > 2 ~ 5V" ; Power off: PS-ON = "Low" or " < 0 ~ 0.5V. So to fix the issue, pson needs 5v positive with M80.

**Comment by dc42** [comment]
Implemented in RRF 3.4.0.
