### ISSUE TITLE
How to get real coordinates while driving?

### ISSUE THREAD

**Issue by selenur** [Duet3D/RepRapFirmware#522]
How to get real coordinates while driving?
If coordinates XY (0:0) and send the command **G1 F10 X100**, then the next command **M114** show the coordinates XY as (100:0), but the real coordinates of the x-axis are not yet 100.

**Comment by PatrikRindlisbacher** [comment]
I discovered the same problem.

With CNC milling, this is elementary.

The display of the coordinates should always be up to date.

**Comment by T3P3** [comment]
you can segment moves and then the co-ordinates will be shown in the segments.

See:
https://docs.duet3d.com/User_manual/Reference/Gcodes#m669-set-kinematics-type-and-kinematics-parameters
Specifically the S&T parameters

please use our forum (forum.duet3d.com) for support.

**Comment by dc42** [comment]
There are two different sets of coordinates: user coordinates and machine coordinates. When the machine is moving, the machine coordinates are kept more up to date than the user coordinates.

**Comment by PatrikRindlisbacher** [comment]
Thanks for the quick reactions.

When CNC milling from CAM, it is **important** to always see the **current** user coordinates G54-G59.

Unfortunately, segmentation is **not** a solution.
.... or I still haven't understood the M669 command. :-)
Is also described very briefly in the help

M669 K0 S4 T0.1 (my attitude V 3.4.0)
G01 Y100 F10
The display immediately jumps to 100mm --> M25 not responding while driving.

It is also very important that the **display is up-to-date** when milling manually with **continuous feed** using a jog box with buttons.
The stop response would be expected as with a **G01 H4** ..... This at the current coordinate when the button is released
