### ISSUE TITLE
How to get the number of the executed command?

### ISSUE THREAD

**Issue by selenur** [Duet3D/RepRapFirmware#524]
Hi!
From my program, I send the following code:
N1 G1 F10 X0 Y0
N2 G1 Y100 X100
.....
N10000 G1 X0
N10001 G1 Y0

When the controller has executed, for example, the command n700 ..... how can I get this number?
My goal is to send 5-10 commands to the controller.

**Comment by chrishamm** [comment]
N specifies the line number. You can read https://github.com/Duet3D/RepRapFirmware/wiki/Object-Model-Documentation#inputslinenumber to get it.
