### ISSUE TITLE
Feature Request: Add a unconditional Motors/Movement Stop button.

### ISSUE THREAD

**Issue by Saur-Hub** [Duet3D/RepRapFirmware#555]
While using movement sometimes it goes out of range if endstop doesn't work or want to move unconditionally it damages parts of the printer. Don't want to use Emergency Stop button for movements as it resets the whole system every time.

**Comment by clearbucketLabs** [comment]
i had this issue, it starts going all over the place.  it's a bit bizarre it would start going other directions if the end stop don't work.  it should keep going in the same direction up to the max of your axis and stop with an error.......  definitely some bug.   i think i'll just move to klipper anyway.
