### ISSUE TITLE
Implicit printer mode change to Cartesian in Dela 3D Printer when M665 fails.

### ISSUE THREAD

**Issue by ghpenguin** [Duet3D/RepRapFirmware#61]
Hi, 

I'm running v1.11-ch.

Once I missed L option for M665 command line in config.g. Then I uploaded it using DWC. 
When I executed G28, the nozzle was heading towards extreme side. It crashed into the side pannel.  
GCode console didn't leave any error message. After reloading config.g, reset, power cycle, the symtom wouldn't go away. 

Out of frustration, I ran M665 without any parameter. 
It reported 'Printer is not Delta mode.'  It's unexpected behavior IMHO.

Does newer version provide alternative way of setting printer type permanently like Marlin? 

Regards,

**Comment by T3P3** [comment]
M665 sets the printer type to delta - if this is in the config.g then it is "permanent" in the sense it is executed on every start up.
