### ISSUE TITLE
Feature Request: Stateful spool tracking

### ISSUE THREAD

**Issue by kag86** [Duet3D/RepRapFirmware#76]
First off, great work on this firmware fork!  Onto my request/thought.

I was just changing a spool today and thought it might be nice if the firmware and web interface had some sort of filament spool states associated with the various tools.  These would track the various extruder movements since the last spool change event(s) was/were issued to the web interface.  Ideally updates to these states would be periodically written to the sdcard to keep the estimates fairly accurate between power cycles.

This feature might be useful for estimates of filament remaining, inventory tracking, and perhaps for optionally auto-pausing a print near the end of spool for those of us without filament detectors.  I've haven't really taken much of a look at the source for this firmware, but I could probably hack up a rough start for what I'm suggesting if you'd like.  I haven't written firmware in about 5 years though, and I'm not terribly familiar with this arduino platform, web programming in general or the build environment.

Regards,
Kyle

**Comment by shoreliner** [comment]
This should be fairly simple to implement -- we've been looking at providing something like this from the M3D side. I'll see what I can do once our current launch is over!

**Comment by dc42** [comment]
Please consult with me and chrishamm first so that we can agree a specification. See https://duet3d.dozuki.com/Wiki/Filaments for what RRF already supports in this area.

**Comment by digi2life** [comment]
I'm all for this feature addition. Markforged does this exactly by having the user enter spool weight when loading filament. The print is auto paused when the spool runs low. You need to know empty spool weight and make sure the remaining amount is stored before power cycle. It works very well.

**Comment by Nightreaver** [comment]
If I may add... after coming from Octoprint.. I was thinking about that at first - https://plugins.octoprint.org/plugins/filamentmanager/

I was a bit sas when it turned out "just" to be for filament specific gcode

**Comment by T3P3** [comment]
This is a candidate for a plugin - please discuss further on the forum.
