### ISSUE TITLE
possible to port to Replicape_BeagleBoneBlack

### ISSUE THREAD

**Issue by BlackStump** [Duet3D/RepRapFirmware#81]
I am jumping in feet first would it be possible for a non programmer to port you firmware to Replicape used on a Beaglebone Black and if so can you point me in the right direction for me to attempt this.
Any advice would be greatly appreciated. (I am already probably over my head but nothing ventured nothing gained)
Thanks

**Comment by dc42** [comment]
It would be difficult. You would need to port the complete hardware abstraction layer (i.e. most of the CoreNG project) first. After that, porting the RepRapFirmware project would be easier after we have changed it to use a real-time operating system, which is planned.
